# Generated by Django 3.1.4 on 2020-12-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatPic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic_name',
            field=models.CharField(default='CatPic', max_length=64),
        ),
        migrations.AlterField(
            model_name='filter',
            name='fil_cat',
            field=models.CharField(default='filter', max_length=32),
        ),
        migrations.AlterField(
            model_name='filter',
            name='fil_text',
            field=models.CharField(default='filter', max_length=128),
        ),
    ]
