# Generated by Django 3.1.4 on 2020-12-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatPic', '0003_auto_20201201_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clowder',
            name='clow_cats',
        ),
        migrations.RemoveField(
            model_name='clowder',
            name='clow_pics',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='pic_cats',
        ),
    ]
