# Generated by Django 3.1.4 on 2020-12-06 23:42

import CatPic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatPic', '0008_auto_20201206_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='pic_cats',
            field=models.JSONField(default=CatPic.models.default_cats),
        ),
    ]
