# Generated by Django 3.1.4 on 2020-12-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatPic', '0009_filter_pic_cats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='pic_cats',
        ),
    ]
